name: CI Pipeline

on:
  push:
    branches: [ "main" ]
# this is strategy for CI if we want use standalone app
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: npm install
    - uses: npm test 
    - run: npm run start


# this is strategy for CI if we want use Docker continer

  #   jobs:

  # build:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Login Dockerhub
  #     env:
  #       DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  #       DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  #     run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
  #   - name: Build the Docker image
  #     run: docker build -t docker-account/app-name .
  #   - name: Push to Dockerhub
  #     run: docker push docker-account/app-name:latest